pipeline_name: "Clients_ingestion"
source:
  format: "json"
  path: "./src_data/clients.csv"
target:
  format: "csv"
  path: "./target_data/clients/"
  mode: "overwrite"
transformations:
  - name: "add_audit_columns"
    logic: "current_timestamp()"